services:
    metamodels.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments:
            - "%metamodels.cache_dir%"

    metamodels.cache.purger:
        class: MetaModels\BackendIntegration\PurgeCache
        arguments:
            - "%metamodels.cache_dir%"
            - "@logger"

    metamodels.factory:
        class: MetaModels\Factory

    metamodels.attribute_factory:
        class: MetaModels\Attribute\AttributeFactory
        arguments:
          - "@event_dispatcher"

    metamodels.filter_setting_factory:
        class: MetaModels\Filter\Setting\FilterSettingFactory
        arguments:
          - "@database_connection"
          - "@event_dispatcher"

    metamodels.render_setting_factory:
        class: MetaModels\Render\Setting\RenderSettingFactory
        arguments:
          - "@database_connection"
          - "@event_dispatcher"

    metamodels.template_list:
        class: MetaModels\BackendIntegration\TemplateList
        arguments:
          - "@database_connection"
          - "%contao.resources_paths%"
          - "%kernel.project_dir%"

    metamodels.insert_tags:
        class: Contao\InsertTags
