services:
    metamodels.provider_from_database:
        class: MetaModels\Events\DatabaseBackedListener
        arguments:
            - "@database_connection"
            - "@cca.legacy_dic"
        tags:
            -   name: kernel.event_listener
                event: metamodels.metamodel.collect-metamodel-attribute-information
                method: collectMetaModelAttributeInformation
            -   name: kernel.event_listener
                event: metamodels.metamodel.collect-table-names
                method: collectMetaModelTableNames
            -   name: kernel.event_listener
                event: metamodels.metamodel.create
                method: createMetaModel
            -   name: kernel.event_listener
                event: metamodels.metamodel.get-metamodel-name-from-id
                method: getMetaModelNameFromId

    metamodels.default_property_condition_creator:
        class: MetaModels\Events\DefaultPropertyConditionCreator
        tags:
            -   name: kernel.event_listener
                event: metamodels.events.create-property-condition-event
                method: handle

    metamodels.property_options_provider:
        class: MetaModels\DcGeneral\Events\MetaModel\PropertyOptionsProvider
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: getPropertyOptions
                # Keep priority low to allow attributes like select and tags to override values.
                priority: -200

    metamodels.pre_duplicate_model_listener:
        class: MetaModels\DcGeneral\Events\MetaModel\DuplicateModel
        arguments:
            - "@metamodels.factory"
        tags:
            -   name: kernel.event_listener
                event: dc-general.model.pre-duplicate
                method: handle
