services:

    ## Service block
    metamodels.factory:
        class: MetaModels\Factory

    metamodels.attribute_factory:
        class: MetaModels\Attribute\AttributeFactory
        arguments:
          - "@event_dispatcher"

    metamodels.filter_setting_factory:
        class: MetaModels\Filter\Setting\FilterSettingFactory
        arguments:
          - "@database_connection"
          - "@event_dispatcher"

    metamodels.filter_setting_factory.idlist:
        class: MetaModels\Filter\Setting\StaticIdListFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_setting_factory.simplelookup:
        class: MetaModels\Filter\Setting\SimpleLookupFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_setting_factory.customsql:
        class: MetaModels\Filter\Setting\CustomSqlFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_setting_factory.conditionand:
        class: MetaModels\Filter\Setting\ConditionAndFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.filter_setting_factory.conditionor:
        class: MetaModels\Filter\Setting\ConditionOrFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }

    metamodels.render_setting_factory:
        class: MetaModels\Render\Setting\RenderSettingFactory

    metamodels.template_list:
        class: MetaModels\BackendIntegration\TemplateList
        arguments:
          - "@database_connection"
          - "%contao.resources_paths%"
          - "%kernel.project_dir%"
