services:

    ## Service block
    metamodels.factory:
        class: MetaModels\Factory

    metamodels.attribute_factory:
        class: MetaModels\Attribute\AttributeFactory

    metamodels.filter_setting_factory:
        class: MetaModels\Filter\Setting\FilterSettingFactory

    metamodels.render_setting_factory:
        class: MetaModels\Render\Setting\RenderSettingFactory


