services:
    metamodels.item_renderer_listener:
        class: MetaModels\CoreBundle\EventListener\DcGeneral\ItemRendererListener
        arguments:
            - "@metamodels.render_setting_factory"
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.model-to-label
                method: render
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.render-readable-property-value
                method: getReadableValue
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-parent-header
                method: addAdditionalParentHeaderFields
